### PR TITLE
Change `push`es to `collect`s and indexing to iteration. Apply clippy lints. Change rustfmt setting.

### PR DESCRIPTION
**Pull request by nothingnesses**
Afaik, collecting an iterator into a collection tends to be faster than pushing elements into an empty instance of that collection (unless the capacity of the empty instance is sufficient), as it minimises the amount of potential reallocations, so I tried to rewrite some of the `push`es into `collect`s. Similarly, iterating through collections tends to be faster than explicit indexing (which usually results in extra bounds-checks, unless unsafe methods are used), so I also tried to rewrite these.

### CODE REVIEW

**Comment by VictorTaelin** [comment]
Sorry, I didn't notice this PR. Yep, my Rust is still a mess when it comes to proper box, vec, etc. usages. Still learning. 

Will try to solve the conflicts tomorrow.

**Comment by nothingnesses** [comment]
@VictorTaelin No worries. I can try to fix the conflicts myself and amend the pull request now if you like.

**Comment by nothingnesses** [comment]
@VictorTaelin I noticed you tend to write some smaller code blocks in one line, so I also changed a rustfmt setting so it now formats the code to fit code blocks in one line if possible (I think the default max width is 100).

**Comment by VictorTaelin** [comment]
Oh damn.

**Comment by nothingnesses** [comment]
@VictorTaelin I've finished resolving the conflicts and the tests seem to pass. Please feel to review at your convenience. I will be AFK for most of today, but if you find anything wrong and let me know, I'll try and get them fixed when I get back later tonight.

**Comment by nothingnesses** [comment]
This PR does seem to make it run slightly faster. As of the current commit, this is what I get when running the program:
```
$ cargo run --release;cargo run --release;cargo run --release;cargo run --release;cargo run --release
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10307.95 rwt/s)
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10357.90 rwt/s)
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10363.34 rwt/s)
    Finished release [optimized] target(s) in 0.13s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10379.05 rwt/s)
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10368.47 rwt/s)
```
and this is with the commits in this PR:
```
$ cargo run --release;cargo run --release;cargo run --release;cargo run --release;cargo run --release
    Finished release [optimized] target(s) in 0.13s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10553.37 rwt/s)
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10585.33 rwt/s)
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10426.78 rwt/s)
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10580.32 rwt/s)
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/lambdavm`
67108864
- rwts: 335544291 (10530.51 rwt/s)
```
I kinda want to try and integrate rayon to see if that will increase the rwt/s some more. It should be easier to do this with the commits in the PR since a lot of the loops have been converted to iterators.

**Pull request merged**
